# Generated by Django 5.1.3 on 2024-11-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_calculationhistory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculationHistory',
        ),
    ]
